import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#loader').hidden);
await page.locator('[data-matter="gas"]').click();await page.waitForTimeout(600);
assert.equal(await page.locator('[data-matter="gas"]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('#chamber-field').getAttribute('data-mode'),'gas');
await page.locator('[data-matter="orbit"]').click();assert.equal(await page.locator('#chamber-field').getAttribute('data-mode'),'orbit');
await page.mouse.move(1000,400);await page.mouse.down();await page.mouse.move(1090,460,{steps:12});await page.mouse.up();
assert(await page.locator('.interaction-ink').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)));
await page.locator('[data-matter="bond"]').click();await page.waitForTimeout(900);await page.screenshot({path:'.frames/matter-interaction.png'});
await page.locator('nav a[href="#work"]').click();await page.waitForTimeout(1400);
await page.locator('[data-orbit="8"]').click();await page.waitForTimeout(1700);assert((await page.locator('#work-current').innerText()).startsWith('09'));
await page.locator('#project-housing .build-link').click();await page.waitForTimeout(1500);assert.equal(await page.locator('#case-select').inputValue(),'housing');
await page.locator('[data-layer="2"]').click();await page.waitForTimeout(1500);assert.equal(await page.locator('[data-layer="2"]').getAttribute('aria-pressed'),'true');
await page.locator('#case-select').selectOption('daymark');await page.waitForFunction(()=>document.querySelector('.case-capture img')?.complete);assert(await page.locator('.case-capture img').evaluate(img=>img.naturalWidth>0));
console.log('Molecular modes, pointer smoke, project dock, anatomy layers and capture passed.');
const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});await mobile.waitForFunction(()=>document.querySelector('#loader').hidden);
await mobile.locator('[data-matter="gas"]').tap();assert.equal(await mobile.locator('#chamber-field').getAttribute('data-mode'),'gas');
await mobile.locator('.chamber-stage').scrollIntoViewIfNeeded();await mobile.waitForTimeout(500);
const box=await mobile.locator('.chamber-stage').boundingBox();await mobile.touchscreen.tap(195,Math.min(650,box.y+box.height/2));
assert.equal(await mobile.locator('#chamber-field').getAttribute('data-touched'),'true');
assert(await mobile.locator('.interaction-ink').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)));
await mobile.screenshot({path:'.frames/matter-touch.png'});
await mobile.emulateMedia({reducedMotion:'reduce'});await mobile.waitForTimeout(300);
assert(await mobile.locator('.interaction-ink').evaluate(c=>!c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)));
console.log('Touch activation and live reduced-motion change passed.');
const fallback=await browser.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return get.call(this,type,...args);};});await fallback.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
assert.equal(await fallback.locator('.matter-fallback').count(),3);assert.equal(await fallback.locator('.project-card').count(),11);console.log('Unavailable WebGL fallback passed.');
assert.deepEqual(errors,[]);await browser.close();
