import './studio.css';
import './cinema.css';
import { createSystemExplorer } from './systemExplorer.js';
import { catalog, repoUrl } from './data/studioCatalog.js';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (url,label,cls='button outline') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
const get=id=>catalog.find(p=>p.id===id);
const featured=[['moneyfest','ai'],['gmat','product'],['buddy','ai'],['davina','creative'],['cafe','product'],['gmat-system','ai']];
const tech=(name,icon,color,ids,description)=>({name,icon,color,ids,description});
const layers=[
 {name:'AI & intelligence',label:'THE REASONING LAYER',items:[tech('Groq','G','#f4ac70',['moneyfest','buddy'],'Structured attribution and verification in MoneyFest; contextual reflections in Buddy.'),tech('Anthropic','A','#d8b198',['moneyfest'],'An alternate provider behind MoneyFest’s shared structured tool-call interface.'),tech('Ollama','◎','#e6e4d9',['gmat-system'],'A local model endpoint powers the GMAT preparation project’s tutoring route.'),tech('pgvector','↗','#a6bcd1',['gmat'],'Vector retrieval infrastructure within the GMAT Trainer’s RAG architecture.'),tech('scikit-learn','sk','#edb479',['housing'],'Regression, classification, SVMs, and neural-network experiments on illustrative datasets.'),tech('n8n','⌘','#e892a4',['cafe'],'Workflow automation is the integration direction described by the Café POS repository.')]},
 {name:'Interfaces & experience',label:'THE EXPERIENCE LAYER',items:[tech('React','⚛','#87c9d9',['davina','buddy','moneyfest','gmat-system'],'Component-driven interfaces across immersive sites, finance tools, and learning products.'),tech('Next.js','N','#efeee5',['gmat','cafe','daymark','tutor'],'Application routing and full-stack web interfaces for practice, productivity, and ordering.'),tech('TypeScript','TS','#8ab6e3',['davina','moneyfest','gmat','cafe','daymark','gmat-system','tutor'],'Typed frontend development across seven public application repositories.'),tech('Three.js','△','#bfcbb5',['davina','gas'],'Procedural 3D scenes, camera movement, and interactive geometry.'),tech('Framer Motion','M','#cea9e6',['davina','buddy'],'Interface transitions and motion choreography in React applications.'),tech('JavaScript','JS','#dfd18c',['buddy','job-agent','gas'],'Product interfaces, backend services, and this interactive portfolio.')]},
 {name:'Services & architecture',label:'THE APPLICATION LAYER',items:[tech('Spring Boot','S','#a6c28b',['gmat','tutor','hcl'],'Java REST services, validation, authentication, and application architecture.'),tech('FastAPI','F','#8bbfb0',['moneyfest','gmat-system'],'Python APIs connecting data pipelines and intelligence to web interfaces.'),tech('Node.js','N','#a4c18b',['buddy','job-agent'],'Express services in Buddy and a native HTTP server in Job-Agent.'),tech('Python','Py','#dfc77d',['moneyfest','gmat','gmat-system','housing'],'Evidence ingestion, extraction, indexing, local AI services, and ML experiments.'),tech('Java','J','#e7a076',['gmat','tutor','first-code','hcl'],'Service architecture and the language foundations behind the learning projects.'),tech('Prisma','◭','#bac6dd',['cafe'],'A typed data layer for products, orders, and historical order-item prices.')]},
 {name:'Data & persistence',label:'THE DATA LAYER',items:[tech('PostgreSQL','Pg','#8eb3ce',['gmat','cafe'],'Relational application storage, migrations, and structured product data.'),tech('SQLite','Sq','#9bbdd1',['moneyfest','gmat-system'],'Local data stores for evidence, attribution history, and extracted practice content.'),tech('Supabase','ϟ','#99cea7',['buddy'],'Backend data integration for the personal finance and planning interface.'),tech('MongoDB','M','#9ec58a',['tutor'],'Document persistence confirmed in the current Spring repositories and entities.'),tech('Local storage','↧','#d8c4a0',['daymark'],'Private browser persistence for daily activity and reflection without an account.'),tech('NumPy','Np','#9faedc',['housing'],'Numerical arrays powering the housing modelling experiments.')]}
];
let activeLayer=0;
function selectTech(index){const t=layers[activeLayer].items[index];$$('.tech').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));$('#tech-evidence').innerHTML=`<p>${esc(t.description)}</p><div class="evidence-links">${t.ids.map(id=>`<button data-project="${id}">${esc(get(id).name)} ↗</button>`).join('')}</div>`;}
function selectLayer(index){activeLayer=index;$$('[data-slab]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.slab)===index))); $$('.stack-tab').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1;});$('#stack-panel').setAttribute('aria-labelledby',`layer-${index}`);$('#layer-label').textContent=layers[index].label;$('#tech-grid').innerHTML=layers[index].items.map((t,i)=>`<button class="tech" data-tech="${i}" aria-pressed="false"><span class="tech-icon" style="--tech-color:${t.color}" aria-hidden="true">${t.icon}</span><span><b>${t.name}</b><small>${String(t.ids.length).padStart(2,'0')} ${t.ids.length===1?'PROJECT':'PROJECTS'}</small></span></button>`).join('');selectTech(0);if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&!document.body.classList.contains('motion-off'))$$('.tech').forEach((el,i)=>el.animate([{opacity:.4,transform:'perspective(600px) rotateX(12deg) translateY(14px)'},{opacity:1,transform:'none'}],{duration:420,delay:i*35,easing:'cubic-bezier(.2,.7,.2,1)'}));}
$('.stack-tabs').innerHTML=layers.map((l,i)=>`<button class="stack-tab" role="tab" id="layer-${i}" aria-controls="stack-panel" data-layer="${i}" aria-selected="false"><span>0${i+1}</span><b>${l.name}</b><i>↗</i></button>`).join('');selectLayer(0);
$('.stack-tabs').addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?3:(activeLayer+(['ArrowUp','ArrowLeft'].includes(e.key)?3:1))%4;selectLayer(n);$(`#layer-${n}`).focus();});
const art={
 moneyfest:`<div class="money-chart">${[23,30,27,40,35,46,38,55,50,65,58,85,74,92,81,96].map((h,i)=>`<i style="--h:${h}%;--d:-${i*.3}s"></i>`).join('')}</div><div class="money-overlay">FROM MARKET MOVEMENT TO MEANING<strong>What moved. And why.</strong><small>GATE → ATTRIBUTE → VERIFY → CITE</small></div>`,
 gmat:'<div class="gmat-window"><div class="gmat-head"><b>GMAT / TRAINER</b><span>VERBAL PRACTICE</span></div><h4>Build the reasoning.<br>Not just the answer.</h4><div class="gmat-option"><span>A</span> Identify the underlying assumption</div><div class="gmat-option selected"><span>B</span> Connect the argument to its evidence</div><div class="gmat-option"><span>C</span> Evaluate a competing explanation</div></div>',
 buddy:`<div class="buddy-orbit"></div><div class="buddy-phone"><small>YOUR EVERYDAY COMPANION</small><h4>A little more balance.</h4><div class="buddy-balance">MONEY · TIME · MOOD<strong>All connected.</strong></div><div class="buddy-bars">${[40,70,55,90,65,80].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div><span class="buddy-caption">A clearer picture of your day ↗</span></div>`,
 davina:'<div class="flight-grid"></div><div class="flight-ring"></div><svg class="drone" viewBox="0 0 210 140" aria-hidden="true"><defs><linearGradient id="metal" x2="1" y2="1"><stop stop-color="#e0e8e8"/><stop offset=".5" stop-color="#6d8794"/><stop offset="1" stop-color="#243e50"/></linearGradient></defs><path d="M102 25L111 25 125 120 104 112 84 120Z" fill="url(#metal)"/><path d="M104 48L200 98 194 110 111 87 104 94 20 115 8 105Z" fill="url(#metal)"/><path d="M102 87L145 127 144 136 107 119 63 136 65 126Z" fill="#7b929c"/><path d="M102 29L107 24 113 60 101 60Z" fill="#172f42"/></svg><span class="flight-copy">DAVINA / AEROSPACE DIGITAL EXPERIENCE</span>',
 cafe:'<div class="flow-art"><div class="flow-node"><b>▤</b><span>ORDER</span></div><div class="flow-node"><b>⌘</b><span>CONNECT</span></div><div class="flow-node"><b>✓</b><span>FULFIL</span></div></div>',
 'gmat-system':'<div class="local-core"><span>LOCAL<br>INTELLIGENCE<br>◎</span></div><span class="local-foot">YOUR CONTENT → YOUR PRACTICE → YOUR TUTOR</span>'
};
const artClass={'moneyfest':'money','gmat':'gmat','buddy':'buddy','davina':'davina','cafe':'cafe','gmat-system':'local'};
function renderProjects(filter='all'){const list=featured.filter(([,type])=>filter==='all'||type===filter);$('#projects').innerHTML=list.map(([id,type])=>{const p=get(id);return `<article class="project-card"><button class="project-art art-${artClass[id]}" data-project="${id}" aria-label="Explore ${esc(p.name)}"><span class="art-meta"><span>${String(featured.findIndex(x=>x[0]===id)+1).padStart(2,'0')} / ${esc(p.type.toUpperCase())}</span><span>INTERFACE / SYSTEM STUDY</span></span>${art[id]}<span class="art-arrow">↗</span></button><div class="project-info"><div class="project-index">FEATURED FRAME / ${String(featured.findIndex(x=>x[0]===id)+1).padStart(2,'0')}</div><div class="project-info-top"><h3><button data-project="${id}">${esc(p.name)}</button></h3><span class="project-type">${type==='ai'?'AI & INTELLIGENCE':type==='creative'?'CREATIVE WEB':'PRODUCT ENGINEERING'}</span></div><p>${esc(p.description)}</p><div class="tags">${p.stack.slice(0,5).map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="project-cta" data-project="${id}">INSIDE THE BUILD <span>↗</span></button></div></article>`;}).join('');}
renderProjects();
function openProject(id){const p=get(id);if(!p)return;$('#archive-dialog').close();$('#project-detail').innerHTML=`<p class="eyebrow">${esc(p.category)}</p><h2 id="dialog-title">${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="tags">${p.stack.map(s=>`<span>${esc(s)}</span>`).join('')}</div>${art[id]?`<div class="detail-art art-${artClass[id]}" aria-hidden="true">${art[id]}</div>`:''}<div class="detail-pipeline">${p.pipeline.map((s,i)=>`<div><small>0${i+1} / SYSTEM LAYER</small>${esc(s)}</div>`).join('')}</div><h3>${esc(p.question)}</h3><p>${esc(p.answer)}</p><h3>Inside the implementation</h3><p>${esc(p.detail)}</p><div class="detail-links">${external(repoUrl(p),'Read the source','button primary')}${p.url?external(p.url,'Open listed preview'):''}</div><div class="source-note">${esc(p.status)} · Public source reviewed September 26, 2026.<br>Repository capabilities are not a claim of production deployment or measured business results.</div>${p.image?`<img class="detail-image" src="${p.image}" alt="${esc(p.name)} public interface, captured September 23, 2026" loading="lazy"><div class="source-note">Public interface capture / September 23, 2026</div>`:''}`;$('#project-dialog').showModal();$('#project-dialog').scrollTop=0;}
function archive(query=''){const rows=catalog.filter(p=>`${p.name} ${p.stack.join(' ')} ${p.description}`.toLowerCase().includes(query.toLowerCase()));$('#archive-results').innerHTML=rows.length?rows.map(p=>`<div class="archive-row"><span>${String(catalog.indexOf(p)+1).padStart(2,'0')}</span><button data-project="${p.id}"><b>${esc(p.name)}</b><small>${esc(p.status)} · ${esc(p.stack.slice(0,3).join(' / '))}</small></button>${external(repoUrl(p),'Source','')}</div>`).join(''):'<p>No projects match. Try a different technology or project name.</p>';}
$('#open-archive').addEventListener('click',()=>{archive();$('#archive-search').value='';$('#archive-dialog').showModal();});$('#archive-search').addEventListener('input',e=>archive(e.target.value));
$$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
const stages=['Collect evidence','Gate movement','Attribute drivers','Verify claims','Cite or abstain'];$('#pipeline').innerHTML=stages.map((s,i)=>`<div class="pipeline-step"><small>0${i+1}</small><b>${s}</b></div>`).join('');
let scenarioTimer;
function scenario(kind,animate=true){clearInterval(scenarioTimer);$$('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===kind)));const noise=kind==='noise';const steps=$$('.pipeline-step');steps.forEach((s,i)=>{s.classList.remove('active');s.classList.toggle('skipped',noise&&i>1);});const output={event:'> eventful movement → INVESTIGATE<br>> candidate claims → verification → citations<br><strong>ATTRIBUTED / surviving evidence retained</strong>',noise:'> movement within ordinary range → NOISE<br>> reasoning layer skipped<br><strong>NOISE / no model call needed</strong>',none:'> eventful movement → INVESTIGATE<br>> candidate claims fail verification<br><strong>NO_DRIVER / uncertainty is a valid answer</strong>'};$('#terminal').innerHTML=output[kind];if(!animate||!motionEnabled){steps.forEach((s,i)=>s.classList.toggle('active',!noise||i<2));return;}let i=0;steps[0].classList.add('active');scenarioTimer=setInterval(()=>{i++;if(i>=(noise?2:5)){clearInterval(scenarioTimer);return;}steps[i].classList.add('active');},350);}
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let motionEnabled=!reduced.matches;let sculpture,systemExplorer;
function updateMotion(){document.body.classList.toggle('motion-off',!motionEnabled);document.documentElement.style.scrollBehavior=motionEnabled?'smooth':'auto';$('#motion-toggle').textContent=`Motion: ${motionEnabled?'on':'off'}`;$('#motion-toggle').setAttribute('aria-pressed',String(!motionEnabled));sculpture?.setMotion(motionEnabled);systemExplorer?.setMotion(motionEnabled);if(!motionEnabled){clearInterval(scenarioTimer);$('#typing').textContent='evidence-driven AI';} }
$('#motion-toggle').addEventListener('click',()=>{motionEnabled=!motionEnabled;updateMotion();});reduced.addEventListener('change',()=>{motionEnabled=!reduced.matches;updateMotion();});updateMotion();scenario('event',false);
import('./visual/StudioSculpture.js').then(({createSculpture})=>{sculpture=createSculpture($('#sculpture'),motionEnabled);sculpture.setExpanded($('#explode-scene').getAttribute('aria-pressed')==='true');}).catch(()=>{/* The static scene remains visible when 3D cannot load. */});
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.project)openProject(t.dataset.project);if(t.dataset.slab!==undefined)selectLayer(Number(t.dataset.slab));if(t.dataset.layer!==undefined)selectLayer(Number(t.dataset.layer));if(t.dataset.tech!==undefined)selectTech(Number(t.dataset.tech));if(t.dataset.filter){$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===t)));renderProjects(t.dataset.filter);}if(t.dataset.scenario)scenario(t.dataset.scenario);});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');observer.unobserve(e.target);}}),{threshold:.08});$$('.section-heading,.stack-layout,.lab-frame,.about-grid').forEach(e=>{e.classList.add('reveal');if(motionEnabled)e.classList.add('pending');observer.observe(e);});
const words=['evidence-driven AI','local-first intelligence','interfaces with feeling','systems that connect'];let wi=0,pos=words[0].length,deleting=true,hold=18;
setInterval(()=>{if(!motionEnabled||document.hidden)return;if(hold-->0)return;const word=words[wi];if(deleting){pos--;if(pos<=0){deleting=false;wi=(wi+1)%words.length;}}else{pos++;if(pos>=words[wi].length){deleting=true;hold=22;}}$('#typing').textContent=words[wi].slice(0,pos);},85);

// Pointer framing adds depth without interfering with native touch scrolling.
$('#projects').addEventListener('pointermove',e=>{if(!motionEnabled||e.pointerType==='touch')return;const card=e.target.closest('.project-art');if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--tilt-x',((e.clientY-r.top)/r.height-.5)*-5+'deg');card.style.setProperty('--tilt-y',((e.clientX-r.left)/r.width-.5)*5+'deg');});
$('#projects').addEventListener('pointerout',e=>{const card=e.target.closest('.project-art');if(card&&!card.contains(e.relatedTarget)){card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg');}});
document.addEventListener('pointerdown',e=>{if(!motionEnabled)return;const target=e.target.closest('.tech,.stack-tab,.button,.scenario-controls button,.system-node,.system-switch button,.scene-control');if(!target)return;const r=target.getBoundingClientRect(),ripple=document.createElement('span');ripple.className='touch-ripple';ripple.style.left=e.clientX-r.left+'px';ripple.style.top=e.clientY-r.top+'px';target.append(ripple);setTimeout(()=>ripple.remove(),650);});

// Explicit controls give the architectural motion a purpose.
let expanded=false;
function expand(){expanded=!expanded;$('#explode-scene').setAttribute('aria-pressed',String(expanded));$('#explode-scene').innerHTML=expanded?'REASSEMBLE THE SYSTEM <span>−</span>':'EXPLODE THE SYSTEM <span>＋</span>';sculpture?.setExpanded(expanded);}
$('#explode-scene').addEventListener('click',expand);$('#sculpture').addEventListener('click',expand);
systemExplorer=createSystemExplorer({motionEnabled:()=>motionEnabled,onScene:()=>{}});
$('.stack-world').addEventListener('pointermove',e=>{if(!motionEnabled||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();$('.layer-tower').style.setProperty('--tower-y',((e.clientX-r.left)/r.width-.5)*9+'deg');});
$('.stack-world').addEventListener('pointerleave',()=>$('.layer-tower').style.setProperty('--tower-y','0deg'));
let scrollFrame=0;
function scrollFrames(){scrollFrame=0;const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--read',max>0?scrollY/max:0);if(!motionEnabled)return;$$('.project-art').forEach(el=>{const rect=el.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight){const f=Math.max(-1,Math.min(1,(rect.top+rect.height/2-innerHeight/2)/innerHeight));el.style.setProperty('--frame-pitch',f*5+'deg');}});const r=$('#about').getBoundingClientRect(),progress=Math.max(-1,Math.min(1,(innerHeight*.5-r.top)/innerHeight));$('.about-word').style.transform='rotateY('+(-22+progress*12)+'deg) rotateX(8deg) translateY('+(-progress*28)+'px)';$$('.contour-frame').forEach((el,i)=>el.style.transform='rotateY('+(-30+progress*14)+'deg) rotateX(30deg) rotateZ('+(25+progress*8)+'deg) translateZ(calc(var(--depth) + '+(progress*i*8)+'px))');}
addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(scrollFrames);},{passive:true});addEventListener('resize',scrollFrames);scrollFrames();
const chapters=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('nav a').forEach(a=>a.classList.toggle('section-active',a.hash==='#'+e.target.id));}}),{rootMargin:'-15% 0px -55% 0px'});$$('#stack,#work,#lab').forEach(el=>chapters.observe(el));
// Close a dialog consistently even when Escape is pressed in its search field.
$$('dialog').forEach(dialog=>dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();dialog.close();}}));
